[package]
name = "is-even-4B"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
is_even_macro = { path = "./is_even_macro" }

[dev-dependencies]
criterion = "0.4"
